### ISSUE TITLE
This project is abandoned

### ISSUE THREAD

**Issue by geroldmeisinger** [sheerun/prettier-standard#137]
Last update in master was on Jul 9, 2020

See https://github.com/ksmithut/prettier-standard

> Note on Fork
> This is a fork of [sheerun/prettier-standard](https://github.com/sheerun/prettier-standard). At the time of forking, it seemed that the project was in need of dependency updates. The author seemed unable to attend to the issues, but it was a package I used and felt strongly enough to do something about it. If the package maintainer returns to maintain the package, I will happily stop work on this and move back over to using that one. In the meantime, I have https://github.com/sheerun/prettier-standard/pull/125 opened there to get dependencies up to date (with breaking node version requirements).

**Comment by gustawdaniel** [comment]
I think that yes.

```
prettier-standard --check
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
TypeError: Cannot read property 'map' of undefined
    at Converter.convertNode (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:2065:53)
    at Converter.converter (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
    at Converter.convertType (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:153:21)
    at Converter.convertNode (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:1793:42)
    at Converter.converter (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
    at Converter.convertChild (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:144:21)
    at /home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:200:32
    at Array.map (<anonymous>)
    at Converter.convertBodyExpressions (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:199:14)
    at Converter.convertNode (/home/daniel/pro/shared/node_modules/prettierx/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:433:32)
```

**Comment by Kikobeats** [comment]
It seems there is a maintained fork: https://github.com/ksmithut/prettier-standard .cc @ksmithut

**Comment by ksmithut** [comment]
I’ve mostly just been keeping dependencies up-to-date. Minor refactoring was done to update major versions of libraries, but no new feature work is planned for my fork.
