### ISSUE TITLE
Ignore node_modules

### ISSUE THREAD

**Issue by StarpTech** [sheerun/prettier-standard#31]
```
> prettier-standard ./packages/hemera-sql-store/**/*.js

prettier-eslint [ERROR]: prettier formatting failed due to a prettier error
prettier-standard [ERROR]: There was an error formatting "./packages/hemera-sql-store/node_modules/resolve/index.js":
    SyntaxError: Unexpected token, expected => (10:7)
       8 |
       9 | exports = async
    > 10 | module.exports = async
         |       ^
      11 |
        at createError$1 (E:\Repositorys\hemera\node_modules\prettier\parser-babylon.js:1:112)
        at parse (E:\Repositorys\hemera\node_modules\prettier\parser-babylon.js:1:808)
        at Object.parse (E:\Repositorys\hemera\node_modules\prettier\index.js:3819:12)
        at formatWithCursor (E:\Repositorys\hemera\node_modules\prettier\index.js:21709:22)
        at format (E:\Repositorys\hemera\node_modules\prettier\index.js:21749:10)
        at Object.format (E:\Repositorys\hemera\node_modules\prettier\index.js:21974:12)
        at prettify (E:\Repositorys\hemera\node_modules\prettier-eslint\dist\index.js:149:29)
        at format (E:\Repositorys\hemera\node_modules\prettier-eslint\dist\index.js:135:20)
        at MapSubscriber.project (E:\Repositorys\hemera\node_modules\prettier-standard\lib\format-files.js:290:55)
        at MapSubscriber._next (E:\Repositorys\hemera\node_modules\rxjs\operator\map.js:77:35)
failure formatting 1 file with prettier-standard
```

.eslintignore
```
!/*.js
/tests/**/*.js
!/tests/**/jsfmt.spec.js
!/**/.eslintrc.js
/test.js
/dist/
**/node_modules/**
/website/static/lib/
/tests_integration/cli/
.nyc_output
coverage
test

```

.prettierignore
```
node_modules
```

**Comment by sheerun** [comment]
I think it's because without quotes it uses shell expansion instead of node.

So following probably should work:

```
prettier-standard './packages/hemera-sql-store/**/*.js'
```

Could you confirm?

**Comment by StarpTech** [comment]
@sheerun when I run `prettier-standard './packages/hemera-sql-store/**/*.js'` nothing happens

```
> hemera@ format E:\Repositorys\hemera
> prettier-standard './packages/hemera-sql-store/**/*.js'

```

when I run `"format": "prettier-standard \"./packages/hemera-sql-store/**/*.js\"",` it takes longer but I get the same error as above.

**Comment by sheerun** [comment]
what happens when you use just prettier?

**Comment by StarpTech** [comment]
When I only use `prettier` it works

**Comment by sheerun** [comment]
I can't reproduce this. In my case prettier-standard ignores all files even in nested node_modules. Maybe you're using old version of prettier-standard?

**Comment by sheerun** [comment]
I think you need to use single quotes
