### ISSUE TITLE
TypeError: eslint.linter.getRules is not a function

### ISSUE THREAD

**Issue by ndelvalle** [sheerun/prettier-standard#38]
Runinig `prettier-standard 'src/**/*.js'` generates the following error:

```
TypeError: eslint.linter.getRules is not a function
    at formatFilesFromArgv (/usr/local/lib/node_modules/prettier-standard/lib/format-files.js:182:19)
    at _callee$ (/usr/local/lib/node_modules/prettier-standard/lib/index.js:22:72)
    at tryCatch (/usr/local/lib/node_modules/prettier-standard/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/prettier-standard/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/prettier-standard/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/prettier-standard/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/prettier-standard/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/prettier-standard/node_modules/core-js/library/modules/_export.js:35:28)
    at /usr/local/lib/node_modules/prettier-standard/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
```

I'm using node `v8.9.3`. Any ideas what might be the problem?

**Comment by sheerun** [comment]
what is the prettier and eslint version in node_modules/eslint/package.json and node_modules/prettier/package.json ?

**Comment by AutoSponge** [comment]
I have the same error:

```
cat node_modules/eslint/package.json | grep 'version'
  "version": "2.13.1"
cat node_modules/prettier/package.json | grep 'version'
  "version": "1.9.2"
```

**Comment by sheerun** [comment]
This should be fixed in prettier-standard@9
