### ISSUE TITLE
[bug] Configuration for rule XXX is invalid

### ISSUE THREAD

**Issue by DoubleU23** [sheerun/prettier-standard#72]
## problem
"prettier-standard" throws Error, parsing some of my EsLint rules

<details>
<summary><strong>full error message</strong></summary>

```
prettier-eslint [ERROR]: There was trouble creating the ESLint CLIEngine.
prettier-standard [ERROR]: There was an error formatting "./utils/testImportExtraneousDeps.js": 
    Error: CLI:
    	Configuration for rule "one-var" is invalid:
    	Value {"initialized":"never","const":"never","var":"consecutive","let":"consecutive","separateRequires":true} should be equal to one of the allowed values.
    	Value {"initialized":"never","const":"never","var":"consecutive","let":"consecutive","separateRequires":true} should NOT have additional properties.
    	Value {"initialized":"never","const":"never","var":"consecutive","let":"consecutive","separateRequires":true} should NOT have additional properties.
    	Value {"initialized":"never","const":"never","var":"consecutive","let":"consecutive","separateRequires":true} should match exactly one schema in oneOf.

        at Object.validateRuleOptions (/var/www/html/tools/logger/node_modules/eslint/lib/config/config-validator.js:133:19)
        at CLIEngine.Object.keys.forEach.name (/var/www/html/tools/logger/node_modules/eslint/lib/cli-engine.js:458:27)
        at Array.forEach (<anonymous>)
        at new CLIEngine (/var/www/html/tools/logger/node_modules/eslint/lib/cli-engine.js:457:45)
        at getESLintCLIEngine (/var/www/html/tools/logger/node_modules/prettier-eslint/dist/utils.js:446:12)
        at eslintFix (/var/www/html/tools/logger/node_modules/prettier-eslint/dist/index.js:180:51)
        at format (/var/www/html/tools/logger/node_modules/prettier-eslint/dist/index.js:149:10)
        at MapSubscriber.project (/var/www/html/tools/logger/node_modules/prettier-standard/src/format-files.js:217:26)
        at MapSubscriber._next (/var/www/html/tools/logger/node_modules/rxjs/operators/map.js:79:35)
        at MapSubscriber.Subscriber.next (/var/www/html/tools/logger/node_modules/rxjs/Subscriber.js:93:18)
failure formatting 1 file with prettier-standard
```
</details>

### (my) rules affected so far:  
<details>
<summary><strong>one-var</strong></summary>

```
    "one-var": ["error", {
      "const": "never",
      "var": "consecutive",
      "let": "consecutive",
      "separateRequires": true
    }],
```
</details>

<details>
<summary><strong>key-spacing</strong></summary>

```
    "key-spacing": ["error", {
        // "mode": "minimum",
        "multiLine": {
            "beforeColon": false,
            "afterColon": true
        },
        "align": {
            "on": "value"
        }
    }],
```
</details>

## my env
__eslint@5.9.0__  
babel-eslint@10.0.1
prettier@1.15
prettier-eslint@8.8.2 (requires __eslint@4.19.1__)
prettier-standard@8.0.1 (requires __eslint@^4.7.2__ and __prettier@1.9.x__)

## ideas
__BTW:__ shouldn't eslint already be dep-required by "prettier-eslint"?  
maybe you should add it as peerDependecy?  

__it's probably 'caused  by a versions-mismatch of eslint/pretty?__  
waiting for #60 to be merged

## additional information  
"prettier-eslint(-cli)" doesn't have problems with that rules

**Comment by sheerun** [comment]
prettier-standard 9.0.0 has been released that respects only `.prettierrc` config and ignores `.eslintrc`. It is because prettier-standard 9 no longer passes code though `eslint --fix`, instead it relies on just `prettierx` (fork of `prettier`) for formatting
